{
 "title": "Cassandra detail custom",
 "description": "Display cassandra node detail in OS, Cassandra and JVM blocks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "up{app=\"cassandracluster\"}"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "label_values(node_filesystem_avail{alias=\"$instance\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Estimated Row Count by Node Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_columnfamily_estimatedrowcount) by (navigator_jetstack_io_cassandra_node_pool_name)",
     "legendFormat": "{{navigator_jetstack_io_cassandra_node_pool_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 }, "content": "Below is the Cassandra metrics" },
  {
   "title": "ColumnFamily Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_readlatency[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ColumnFamily Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_writelatency[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_clientrequest_latency{alias=\"$instance\"} [5m])",
     "legendFormat": "{{clientrequest}}"
    }
   ]
  },
  {
   "title": "Keyspace live disk usgae",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_livediskspaceused) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "memtable live data size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_memtablelivedatasize) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Keyspace Range latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_keyspace_rangelatency{alias=\"$instance\"}[5m])",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Client count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{alias=\"$instance\"}",
     "legendFormat": "Native"
    },
    {
     "expr": "cassandra_client_connectedthriftclients{alias=\"$instance\"}",
     "legendFormat": "Thrift"
    }
   ]
  },
  {
   "title": "Cache capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_capacity{alias=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Disk I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{alias=\"$instance\"}[5m]) * 1024 or irate(node_vmstat_pgpgin{alias=\"$instance\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{alias=\"$instance\"}[5m]) * 1024 or irate(node_vmstat_pgpgout{alias=\"$instance\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",alias=\"$instance\"} / jvm_memory_bytes_max{area=\"heap\", alias=\"$instance\"}",
     "legendFormat": "heap"
    }
   ]
  },
  {
   "title": "Memory Pool used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{alias=\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_sum{alias=\"$instance\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}