apiVersion: "navigator.jetstack.io/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: "demo"
spec:
  cqlPort: 9042
  sysctls:
  - "vm.max_map_count=0"
  nodePools:
  - name: "ringnodes"
    replicas: 3
    datacenter: "demo-datacenter"
    rack: "demo-rack"
    persistence:
      enabled: true
      size: "5Gi"
      storageClass: "default"
    nodeSelector:
  image:
    repository: "cassandra"
    tag: "3"
    pullPolicy: "IfNotPresent"
  pilotImage:
    repository: "jetstackexperimental/navigator-pilot-cassandra"
    tag: "canary"
