apiVersion: navigator.jetstack.io/v1alpha1
kind: ElasticsearchCluster
metadata:
  name: demo
spec:
  sysctl:
  - vm.max_map_count=262144

  pilot:
    repository: jetstackexperimental/navigator-pilot-elasticsearch
    tag: latest
    pullPolicy: Always

  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 5.6.2
    pullPolicy: Always
    ## This sets the group of the persistent volume created for
    ## the data nodes. This must be the same as the user that elasticsearch
    ## runs as within the container.
    fsGroup: 1000

  nodePools:
  - name: MasterPool
    replicas: 3

    roles:
    - master

    config:
      elasticsearch.yml: |
        node.data: ${NODE_DATA}
        node.master: ${NODE_MASTER}
        node.ingest: ${NODE_INGEST}
        node.name: ${POD_NAME}

        network.host: 0.0.0.0

        discovery:
          zen:
            ping.unicast.hosts: ${DISCOVERY_URL}
            minimum_master_nodes: 2

        xpack.security.enabled: false

    resources:
      requests:
        cpu: '500m'
        memory: 2Gi
      limits:
        cpu: '1'
        memory: 3Gi

    persistence:
      enabled: true
      # size of the volume
      size: 10Gi
      # storageClass of the volume
      storageClass: standard

  - name: mixed
    replicas: 2

    roles:
    - data
    - ingest

    config:
      elasticsearch.yml: |
        node.data: ${NODE_DATA}
        node.master: ${NODE_MASTER}
        node.ingest: ${NODE_INGEST}
        node.name: ${POD_NAME}

        network.host: 0.0.0.0

        discovery:
          zen:
            ping.unicast.hosts: ${DISCOVERY_URL}
            minimum_master_nodes: 2

        xpack.security.enabled: false

    resources:
      requests:
        cpu: '500m'
        memory: 2Gi
      limits:
        cpu: '1'
        memory: 3Gi

    persistence:
      enabled: true
      # size of the volume
      size: 10Gi
      # storageClass of the volume
      storageClass: standard
