// Code generated by protoc-gen-go.
// source: pkg/api/v1/types.proto
// DO NOT EDIT!

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	pkg/api/v1/types.proto

It has these top-level messages:
	ElasticsearchClusterSpec
	ElasticsearchClusterPlugin
	ElasticsearchClusterNodePool
	ElasticsearchClusterResources
	ElasticsearchClusterPersistenceConfig
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ElasticsearchClusterSpec struct {
	Version   string                          `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Plugins   []*ElasticsearchClusterPlugin   `protobuf:"bytes,2,rep,name=plugins" json:"plugins,omitempty"`
	NodePools []*ElasticsearchClusterNodePool `protobuf:"bytes,3,rep,name=nodePools" json:"nodePools,omitempty"`
}

func (m *ElasticsearchClusterSpec) Reset()                    { *m = ElasticsearchClusterSpec{} }
func (m *ElasticsearchClusterSpec) String() string            { return proto.CompactTextString(m) }
func (*ElasticsearchClusterSpec) ProtoMessage()               {}
func (*ElasticsearchClusterSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ElasticsearchClusterSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ElasticsearchClusterSpec) GetPlugins() []*ElasticsearchClusterPlugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *ElasticsearchClusterSpec) GetNodePools() []*ElasticsearchClusterNodePool {
	if m != nil {
		return m.NodePools
	}
	return nil
}

type ElasticsearchClusterPlugin struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ElasticsearchClusterPlugin) Reset()                    { *m = ElasticsearchClusterPlugin{} }
func (m *ElasticsearchClusterPlugin) String() string            { return proto.CompactTextString(m) }
func (*ElasticsearchClusterPlugin) ProtoMessage()               {}
func (*ElasticsearchClusterPlugin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ElasticsearchClusterPlugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ElasticsearchClusterNodePool struct {
	Name      string                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Replicas  int64                          `protobuf:"varint,2,opt,name=replicas" json:"replicas,omitempty"`
	Roles     []string                       `protobuf:"bytes,3,rep,name=roles" json:"roles,omitempty"`
	Resources *ElasticsearchClusterResources `protobuf:"bytes,4,opt,name=resources" json:"resources,omitempty"`
}

func (m *ElasticsearchClusterNodePool) Reset()                    { *m = ElasticsearchClusterNodePool{} }
func (m *ElasticsearchClusterNodePool) String() string            { return proto.CompactTextString(m) }
func (*ElasticsearchClusterNodePool) ProtoMessage()               {}
func (*ElasticsearchClusterNodePool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ElasticsearchClusterNodePool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ElasticsearchClusterNodePool) GetReplicas() int64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *ElasticsearchClusterNodePool) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ElasticsearchClusterNodePool) GetResources() *ElasticsearchClusterResources {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig struct {
	Stateful    bool                                   `protobuf:"varint,1,opt,name=stateful" json:"stateful,omitempty"`
	Persistence *ElasticsearchClusterPersistenceConfig `protobuf:"bytes,2,opt,name=persistence" json:"persistence,omitempty"`
}

func (m *ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig) Reset() {
	*m = ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig{}
}
func (m *ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig) String() string {
	return proto.CompactTextString(m)
}
func (*ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig) ProtoMessage() {}
func (*ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig) GetStateful() bool {
	if m != nil {
		return m.Stateful
	}
	return false
}

func (m *ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig) GetPersistence() *ElasticsearchClusterPersistenceConfig {
	if m != nil {
		return m.Persistence
	}
	return nil
}

type ElasticsearchClusterResources struct {
	Requests *ElasticsearchClusterResources_ResourceSet `protobuf:"bytes,1,opt,name=requests" json:"requests,omitempty"`
	Limits   *ElasticsearchClusterResources_ResourceSet `protobuf:"bytes,2,opt,name=limits" json:"limits,omitempty"`
}

func (m *ElasticsearchClusterResources) Reset()                    { *m = ElasticsearchClusterResources{} }
func (m *ElasticsearchClusterResources) String() string            { return proto.CompactTextString(m) }
func (*ElasticsearchClusterResources) ProtoMessage()               {}
func (*ElasticsearchClusterResources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ElasticsearchClusterResources) GetRequests() *ElasticsearchClusterResources_ResourceSet {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *ElasticsearchClusterResources) GetLimits() *ElasticsearchClusterResources_ResourceSet {
	if m != nil {
		return m.Limits
	}
	return nil
}

type ElasticsearchClusterResources_ResourceSet struct {
	CPU    string `protobuf:"bytes,1,opt,name=CPU" json:"CPU,omitempty"`
	Memory string `protobuf:"bytes,2,opt,name=memory" json:"memory,omitempty"`
}

func (m *ElasticsearchClusterResources_ResourceSet) Reset() {
	*m = ElasticsearchClusterResources_ResourceSet{}
}
func (m *ElasticsearchClusterResources_ResourceSet) String() string { return proto.CompactTextString(m) }
func (*ElasticsearchClusterResources_ResourceSet) ProtoMessage()    {}
func (*ElasticsearchClusterResources_ResourceSet) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

func (m *ElasticsearchClusterResources_ResourceSet) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *ElasticsearchClusterResources_ResourceSet) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

type ElasticsearchClusterPersistenceConfig struct {
	Enabled      bool   `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	Size         string `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	StorageClass string `protobuf:"bytes,3,opt,name=storageClass" json:"storageClass,omitempty"`
}

func (m *ElasticsearchClusterPersistenceConfig) Reset()         { *m = ElasticsearchClusterPersistenceConfig{} }
func (m *ElasticsearchClusterPersistenceConfig) String() string { return proto.CompactTextString(m) }
func (*ElasticsearchClusterPersistenceConfig) ProtoMessage()    {}
func (*ElasticsearchClusterPersistenceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *ElasticsearchClusterPersistenceConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ElasticsearchClusterPersistenceConfig) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *ElasticsearchClusterPersistenceConfig) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

func init() {
	proto.RegisterType((*ElasticsearchClusterSpec)(nil), "v1.ElasticsearchClusterSpec")
	proto.RegisterType((*ElasticsearchClusterPlugin)(nil), "v1.ElasticsearchClusterPlugin")
	proto.RegisterType((*ElasticsearchClusterNodePool)(nil), "v1.ElasticsearchClusterNodePool")
	proto.RegisterType((*ElasticsearchClusterNodePool_ElasticsearchClusterStateConfig)(nil), "v1.ElasticsearchClusterNodePool.ElasticsearchClusterStateConfig")
	proto.RegisterType((*ElasticsearchClusterResources)(nil), "v1.ElasticsearchClusterResources")
	proto.RegisterType((*ElasticsearchClusterResources_ResourceSet)(nil), "v1.ElasticsearchClusterResources.ResourceSet")
	proto.RegisterType((*ElasticsearchClusterPersistenceConfig)(nil), "v1.ElasticsearchClusterPersistenceConfig")
}

func init() { proto.RegisterFile("pkg/api/v1/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0xda, 0xa5, 0xbb, 0x99, 0x70, 0x40, 0x16, 0x5a, 0x45, 0x15, 0x3f, 0x25, 0x12, 0x52,
	0x39, 0xd0, 0xd2, 0x72, 0x80, 0x13, 0x1c, 0xaa, 0x3d, 0x20, 0x24, 0x54, 0x79, 0xc5, 0x03, 0x78,
	0xb3, 0xb3, 0xc5, 0xc2, 0x8d, 0x8d, 0xc7, 0x89, 0x54, 0x1e, 0x81, 0x87, 0xe1, 0xc0, 0x63, 0xf1,
	0x14, 0xc8, 0xae, 0xd3, 0x2e, 0x52, 0x53, 0xd8, 0xdb, 0x7c, 0xc9, 0xf7, 0x7d, 0xfe, 0x66, 0xc6,
	0x86, 0x73, 0xf3, 0x75, 0x35, 0x15, 0x46, 0x4e, 0x9b, 0xd9, 0xd4, 0x6d, 0x0c, 0xd2, 0xc4, 0x58,
	0xed, 0x34, 0xeb, 0x35, 0xb3, 0xe2, 0x67, 0x02, 0xf9, 0x85, 0x12, 0xe4, 0x64, 0x49, 0x28, 0x6c,
	0xf9, 0x65, 0xa1, 0x6a, 0x72, 0x68, 0x2f, 0x0d, 0x96, 0x2c, 0x87, 0xd3, 0x06, 0x2d, 0x49, 0x5d,
	0xe5, 0xc9, 0x28, 0x19, 0xa7, 0xbc, 0x85, 0xec, 0x2d, 0x9c, 0x1a, 0x55, 0xaf, 0x64, 0x45, 0x79,
	0x6f, 0xd4, 0x1f, 0x67, 0xf3, 0x27, 0x93, 0x66, 0x36, 0x39, 0x64, 0xb4, 0x0c, 0x34, 0xde, 0xd2,
	0xd9, 0x3b, 0x48, 0x2b, 0x7d, 0x8d, 0x4b, 0xad, 0x15, 0xe5, 0xfd, 0xa0, 0x1d, 0x75, 0x69, 0x3f,
	0x45, 0x22, 0xdf, 0x4b, 0x8a, 0x57, 0x30, 0xec, 0x3e, 0x86, 0x31, 0x38, 0xa9, 0xc4, 0x1a, 0x63,
	0xdc, 0x50, 0x17, 0xbf, 0x7a, 0xf0, 0xe8, 0x98, 0xfb, 0x21, 0x11, 0x1b, 0xc2, 0x99, 0x45, 0xa3,
	0x64, 0x29, 0x7c, 0x87, 0xc9, 0xb8, 0xcf, 0x77, 0x98, 0x3d, 0x84, 0x7b, 0x56, 0x2b, 0xdc, 0xc6,
	0x4f, 0xf9, 0x16, 0xb0, 0xf7, 0x90, 0x5a, 0x24, 0x5d, 0xdb, 0x12, 0x29, 0x3f, 0x19, 0x25, 0xe3,
	0x6c, 0xfe, 0xac, 0xab, 0x31, 0xde, 0x12, 0xf9, 0x5e, 0x33, 0xfc, 0x91, 0xc0, 0xd3, 0x83, 0xab,
	0x70, 0xc2, 0xe1, 0x42, 0x57, 0x37, 0x72, 0xe5, 0x63, 0x91, 0x87, 0x37, 0xb5, 0x0a, 0x71, 0xcf,
	0xf8, 0x0e, 0xb3, 0x8f, 0x90, 0x19, 0xbf, 0x1e, 0x72, 0x58, 0x95, 0x18, 0x52, 0x67, 0xf3, 0x17,
	0x9d, 0x7b, 0xd9, 0x53, 0xb7, 0xde, 0xfc, 0xb6, 0xba, 0xf8, 0x9d, 0xc0, 0xe3, 0xa3, 0xc9, 0xd9,
	0x07, 0x3f, 0xa1, 0x6f, 0x35, 0x92, 0xa3, 0x10, 0x25, 0x9b, 0xbf, 0xfc, 0x67, 0xbb, 0x93, 0xb6,
	0xba, 0x44, 0xc7, 0x77, 0x72, 0x76, 0x01, 0x03, 0x25, 0xd7, 0xd2, 0x51, 0x0c, 0x7d, 0x47, 0xa3,
	0x28, 0x1e, 0xbe, 0x81, 0xec, 0xd6, 0x67, 0xf6, 0x00, 0xfa, 0x8b, 0xe5, 0xe7, 0xb8, 0x55, 0x5f,
	0xb2, 0x73, 0x18, 0xac, 0x71, 0xad, 0xed, 0x26, 0x9c, 0x93, 0xf2, 0x88, 0x8a, 0x0d, 0x3c, 0xff,
	0xaf, 0x11, 0xf9, 0x07, 0x81, 0x95, 0xb8, 0x52, 0x78, 0x1d, 0xa7, 0xdf, 0x42, 0x7f, 0x87, 0x48,
	0x7e, 0xc7, 0x68, 0x1c, 0x6a, 0x56, 0xc0, 0x7d, 0x72, 0xda, 0x8a, 0x15, 0x2e, 0x94, 0x20, 0x7f,
	0x5d, 0xfc, 0xbf, 0xbf, 0xbe, 0x5d, 0x0d, 0xc2, 0x53, 0x7c, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x24, 0x81, 0xe9, 0x87, 0xa4, 0x03, 0x00, 0x00,
}
