load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["common.go"],
    importpath = "github.com/jetstack/navigator/pkg/controllers/common",
    visibility = ["//visibility:public"],
)
