/*
Copyright 2018 Jetstack Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

// CassandraClusterListerExpansion allows custom methods to be added to
// CassandraClusterLister.
type CassandraClusterListerExpansion interface{}

// CassandraClusterNamespaceListerExpansion allows custom methods to be added to
// CassandraClusterNamespaceLister.
type CassandraClusterNamespaceListerExpansion interface{}

// ElasticsearchClusterListerExpansion allows custom methods to be added to
// ElasticsearchClusterLister.
type ElasticsearchClusterListerExpansion interface{}

// ElasticsearchClusterNamespaceListerExpansion allows custom methods to be added to
// ElasticsearchClusterNamespaceLister.
type ElasticsearchClusterNamespaceListerExpansion interface{}

// PilotListerExpansion allows custom methods to be added to
// PilotLister.
type PilotListerExpansion interface{}

// PilotNamespaceListerExpansion allows custom methods to be added to
// PilotNamespaceLister.
type PilotNamespaceListerExpansion interface{}
