// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	marshal "github.com/jetstack-experimental/navigator/pkg/apis/marshal"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/pkg/api/v1"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ElasticsearchCluster_To_marshal_ElasticsearchCluster,
		Convert_marshal_ElasticsearchCluster_To_v1alpha1_ElasticsearchCluster,
		Convert_v1alpha1_ElasticsearchClusterList_To_marshal_ElasticsearchClusterList,
		Convert_marshal_ElasticsearchClusterList_To_v1alpha1_ElasticsearchClusterList,
		Convert_v1alpha1_ElasticsearchClusterNodePool_To_marshal_ElasticsearchClusterNodePool,
		Convert_marshal_ElasticsearchClusterNodePool_To_v1alpha1_ElasticsearchClusterNodePool,
		Convert_v1alpha1_ElasticsearchClusterPersistenceConfig_To_marshal_ElasticsearchClusterPersistenceConfig,
		Convert_marshal_ElasticsearchClusterPersistenceConfig_To_v1alpha1_ElasticsearchClusterPersistenceConfig,
		Convert_v1alpha1_ElasticsearchClusterPlugin_To_marshal_ElasticsearchClusterPlugin,
		Convert_marshal_ElasticsearchClusterPlugin_To_v1alpha1_ElasticsearchClusterPlugin,
		Convert_v1alpha1_ElasticsearchClusterSpec_To_marshal_ElasticsearchClusterSpec,
		Convert_marshal_ElasticsearchClusterSpec_To_v1alpha1_ElasticsearchClusterSpec,
		Convert_v1alpha1_ElasticsearchClusterStatus_To_marshal_ElasticsearchClusterStatus,
		Convert_marshal_ElasticsearchClusterStatus_To_v1alpha1_ElasticsearchClusterStatus,
		Convert_v1alpha1_ElasticsearchImage_To_marshal_ElasticsearchImage,
		Convert_marshal_ElasticsearchImage_To_v1alpha1_ElasticsearchImage,
	)
}

func autoConvert_v1alpha1_ElasticsearchCluster_To_marshal_ElasticsearchCluster(in *ElasticsearchCluster, out *marshal.ElasticsearchCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ElasticsearchClusterSpec_To_marshal_ElasticsearchClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ElasticsearchClusterStatus_To_marshal_ElasticsearchClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ElasticsearchCluster_To_marshal_ElasticsearchCluster is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchCluster_To_marshal_ElasticsearchCluster(in *ElasticsearchCluster, out *marshal.ElasticsearchCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchCluster_To_marshal_ElasticsearchCluster(in, out, s)
}

func autoConvert_marshal_ElasticsearchCluster_To_v1alpha1_ElasticsearchCluster(in *marshal.ElasticsearchCluster, out *ElasticsearchCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_marshal_ElasticsearchClusterSpec_To_v1alpha1_ElasticsearchClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_marshal_ElasticsearchClusterStatus_To_v1alpha1_ElasticsearchClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_marshal_ElasticsearchCluster_To_v1alpha1_ElasticsearchCluster is an autogenerated conversion function.
func Convert_marshal_ElasticsearchCluster_To_v1alpha1_ElasticsearchCluster(in *marshal.ElasticsearchCluster, out *ElasticsearchCluster, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchCluster_To_v1alpha1_ElasticsearchCluster(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchClusterList_To_marshal_ElasticsearchClusterList(in *ElasticsearchClusterList, out *marshal.ElasticsearchClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]marshal.ElasticsearchCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ElasticsearchClusterList_To_marshal_ElasticsearchClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchClusterList_To_marshal_ElasticsearchClusterList(in *ElasticsearchClusterList, out *marshal.ElasticsearchClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchClusterList_To_marshal_ElasticsearchClusterList(in, out, s)
}

func autoConvert_marshal_ElasticsearchClusterList_To_v1alpha1_ElasticsearchClusterList(in *marshal.ElasticsearchClusterList, out *ElasticsearchClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]ElasticsearchCluster, 0)
	} else {
		out.Items = *(*[]ElasticsearchCluster)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_marshal_ElasticsearchClusterList_To_v1alpha1_ElasticsearchClusterList is an autogenerated conversion function.
func Convert_marshal_ElasticsearchClusterList_To_v1alpha1_ElasticsearchClusterList(in *marshal.ElasticsearchClusterList, out *ElasticsearchClusterList, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchClusterList_To_v1alpha1_ElasticsearchClusterList(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchClusterNodePool_To_marshal_ElasticsearchClusterNodePool(in *ElasticsearchClusterNodePool, out *marshal.ElasticsearchClusterNodePool, s conversion.Scope) error {
	out.Name = in.Name
	out.Replicas = in.Replicas
	out.Roles = *(*[]string)(unsafe.Pointer(&in.Roles))
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Persistence = (*marshal.ElasticsearchClusterPersistenceConfig)(unsafe.Pointer(in.Persistence))
	return nil
}

// Convert_v1alpha1_ElasticsearchClusterNodePool_To_marshal_ElasticsearchClusterNodePool is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchClusterNodePool_To_marshal_ElasticsearchClusterNodePool(in *ElasticsearchClusterNodePool, out *marshal.ElasticsearchClusterNodePool, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchClusterNodePool_To_marshal_ElasticsearchClusterNodePool(in, out, s)
}

func autoConvert_marshal_ElasticsearchClusterNodePool_To_v1alpha1_ElasticsearchClusterNodePool(in *marshal.ElasticsearchClusterNodePool, out *ElasticsearchClusterNodePool, s conversion.Scope) error {
	out.Name = in.Name
	out.Replicas = in.Replicas
	if in.Roles == nil {
		out.Roles = make([]string, 0)
	} else {
		out.Roles = *(*[]string)(unsafe.Pointer(&in.Roles))
	}
	out.Resources = (*v1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.Persistence = (*ElasticsearchClusterPersistenceConfig)(unsafe.Pointer(in.Persistence))
	return nil
}

// Convert_marshal_ElasticsearchClusterNodePool_To_v1alpha1_ElasticsearchClusterNodePool is an autogenerated conversion function.
func Convert_marshal_ElasticsearchClusterNodePool_To_v1alpha1_ElasticsearchClusterNodePool(in *marshal.ElasticsearchClusterNodePool, out *ElasticsearchClusterNodePool, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchClusterNodePool_To_v1alpha1_ElasticsearchClusterNodePool(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchClusterPersistenceConfig_To_marshal_ElasticsearchClusterPersistenceConfig(in *ElasticsearchClusterPersistenceConfig, out *marshal.ElasticsearchClusterPersistenceConfig, s conversion.Scope) error {
	out.Size = in.Size
	out.StorageClass = in.StorageClass
	return nil
}

// Convert_v1alpha1_ElasticsearchClusterPersistenceConfig_To_marshal_ElasticsearchClusterPersistenceConfig is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchClusterPersistenceConfig_To_marshal_ElasticsearchClusterPersistenceConfig(in *ElasticsearchClusterPersistenceConfig, out *marshal.ElasticsearchClusterPersistenceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchClusterPersistenceConfig_To_marshal_ElasticsearchClusterPersistenceConfig(in, out, s)
}

func autoConvert_marshal_ElasticsearchClusterPersistenceConfig_To_v1alpha1_ElasticsearchClusterPersistenceConfig(in *marshal.ElasticsearchClusterPersistenceConfig, out *ElasticsearchClusterPersistenceConfig, s conversion.Scope) error {
	out.Size = in.Size
	out.StorageClass = in.StorageClass
	return nil
}

// Convert_marshal_ElasticsearchClusterPersistenceConfig_To_v1alpha1_ElasticsearchClusterPersistenceConfig is an autogenerated conversion function.
func Convert_marshal_ElasticsearchClusterPersistenceConfig_To_v1alpha1_ElasticsearchClusterPersistenceConfig(in *marshal.ElasticsearchClusterPersistenceConfig, out *ElasticsearchClusterPersistenceConfig, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchClusterPersistenceConfig_To_v1alpha1_ElasticsearchClusterPersistenceConfig(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchClusterPlugin_To_marshal_ElasticsearchClusterPlugin(in *ElasticsearchClusterPlugin, out *marshal.ElasticsearchClusterPlugin, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ElasticsearchClusterPlugin_To_marshal_ElasticsearchClusterPlugin is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchClusterPlugin_To_marshal_ElasticsearchClusterPlugin(in *ElasticsearchClusterPlugin, out *marshal.ElasticsearchClusterPlugin, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchClusterPlugin_To_marshal_ElasticsearchClusterPlugin(in, out, s)
}

func autoConvert_marshal_ElasticsearchClusterPlugin_To_v1alpha1_ElasticsearchClusterPlugin(in *marshal.ElasticsearchClusterPlugin, out *ElasticsearchClusterPlugin, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_marshal_ElasticsearchClusterPlugin_To_v1alpha1_ElasticsearchClusterPlugin is an autogenerated conversion function.
func Convert_marshal_ElasticsearchClusterPlugin_To_v1alpha1_ElasticsearchClusterPlugin(in *marshal.ElasticsearchClusterPlugin, out *ElasticsearchClusterPlugin, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchClusterPlugin_To_v1alpha1_ElasticsearchClusterPlugin(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchClusterSpec_To_marshal_ElasticsearchClusterSpec(in *ElasticsearchClusterSpec, out *marshal.ElasticsearchClusterSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Plugins = *(*[]marshal.ElasticsearchClusterPlugin)(unsafe.Pointer(&in.Plugins))
	out.NodePools = *(*[]marshal.ElasticsearchClusterNodePool)(unsafe.Pointer(&in.NodePools))
	if err := Convert_v1alpha1_ElasticsearchImage_To_marshal_ElasticsearchImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.Sysctl = *(*[]string)(unsafe.Pointer(&in.Sysctl))
	return nil
}

// Convert_v1alpha1_ElasticsearchClusterSpec_To_marshal_ElasticsearchClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchClusterSpec_To_marshal_ElasticsearchClusterSpec(in *ElasticsearchClusterSpec, out *marshal.ElasticsearchClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchClusterSpec_To_marshal_ElasticsearchClusterSpec(in, out, s)
}

func autoConvert_marshal_ElasticsearchClusterSpec_To_v1alpha1_ElasticsearchClusterSpec(in *marshal.ElasticsearchClusterSpec, out *ElasticsearchClusterSpec, s conversion.Scope) error {
	out.Version = in.Version
	if in.Plugins == nil {
		out.Plugins = make([]ElasticsearchClusterPlugin, 0)
	} else {
		out.Plugins = *(*[]ElasticsearchClusterPlugin)(unsafe.Pointer(&in.Plugins))
	}
	if in.NodePools == nil {
		out.NodePools = make([]ElasticsearchClusterNodePool, 0)
	} else {
		out.NodePools = *(*[]ElasticsearchClusterNodePool)(unsafe.Pointer(&in.NodePools))
	}
	if err := Convert_marshal_ElasticsearchImage_To_v1alpha1_ElasticsearchImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	if in.Sysctl == nil {
		out.Sysctl = make([]string, 0)
	} else {
		out.Sysctl = *(*[]string)(unsafe.Pointer(&in.Sysctl))
	}
	return nil
}

// Convert_marshal_ElasticsearchClusterSpec_To_v1alpha1_ElasticsearchClusterSpec is an autogenerated conversion function.
func Convert_marshal_ElasticsearchClusterSpec_To_v1alpha1_ElasticsearchClusterSpec(in *marshal.ElasticsearchClusterSpec, out *ElasticsearchClusterSpec, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchClusterSpec_To_v1alpha1_ElasticsearchClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchClusterStatus_To_marshal_ElasticsearchClusterStatus(in *ElasticsearchClusterStatus, out *marshal.ElasticsearchClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ElasticsearchClusterStatus_To_marshal_ElasticsearchClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchClusterStatus_To_marshal_ElasticsearchClusterStatus(in *ElasticsearchClusterStatus, out *marshal.ElasticsearchClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchClusterStatus_To_marshal_ElasticsearchClusterStatus(in, out, s)
}

func autoConvert_marshal_ElasticsearchClusterStatus_To_v1alpha1_ElasticsearchClusterStatus(in *marshal.ElasticsearchClusterStatus, out *ElasticsearchClusterStatus, s conversion.Scope) error {
	return nil
}

// Convert_marshal_ElasticsearchClusterStatus_To_v1alpha1_ElasticsearchClusterStatus is an autogenerated conversion function.
func Convert_marshal_ElasticsearchClusterStatus_To_v1alpha1_ElasticsearchClusterStatus(in *marshal.ElasticsearchClusterStatus, out *ElasticsearchClusterStatus, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchClusterStatus_To_v1alpha1_ElasticsearchClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_ElasticsearchImage_To_marshal_ElasticsearchImage(in *ElasticsearchImage, out *marshal.ElasticsearchImage, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Tag = in.Tag
	out.PullPolicy = in.PullPolicy
	out.FsGroup = in.FsGroup
	return nil
}

// Convert_v1alpha1_ElasticsearchImage_To_marshal_ElasticsearchImage is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchImage_To_marshal_ElasticsearchImage(in *ElasticsearchImage, out *marshal.ElasticsearchImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchImage_To_marshal_ElasticsearchImage(in, out, s)
}

func autoConvert_marshal_ElasticsearchImage_To_v1alpha1_ElasticsearchImage(in *marshal.ElasticsearchImage, out *ElasticsearchImage, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Tag = in.Tag
	out.PullPolicy = in.PullPolicy
	out.FsGroup = in.FsGroup
	return nil
}

// Convert_marshal_ElasticsearchImage_To_v1alpha1_ElasticsearchImage is an autogenerated conversion function.
func Convert_marshal_ElasticsearchImage_To_v1alpha1_ElasticsearchImage(in *marshal.ElasticsearchImage, out *ElasticsearchImage, s conversion.Scope) error {
	return autoConvert_marshal_ElasticsearchImage_To_v1alpha1_ElasticsearchImage(in, out, s)
}
