/*
Copyright 2017 Jetstack Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	navigator_v1alpha1 "github.com/jetstack-experimental/navigator/pkg/apis/navigator/v1alpha1"
	clientset "github.com/jetstack-experimental/navigator/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/jetstack-experimental/navigator/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/jetstack-experimental/navigator/pkg/client/listers_generated/navigator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// CassandraClusterInformer provides access to a shared informer and lister for
// CassandraClusters.
type CassandraClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CassandraClusterLister
}

type cassandraClusterInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewCassandraClusterInformer constructs a new informer for CassandraCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCassandraClusterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.NavigatorV1alpha1().CassandraClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.NavigatorV1alpha1().CassandraClusters(namespace).Watch(options)
			},
		},
		&navigator_v1alpha1.CassandraCluster{},
		resyncPeriod,
		indexers,
	)
}

func defaultCassandraClusterInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewCassandraClusterInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *cassandraClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&navigator_v1alpha1.CassandraCluster{}, defaultCassandraClusterInformer)
}

func (f *cassandraClusterInformer) Lister() v1alpha1.CassandraClusterLister {
	return v1alpha1.NewCassandraClusterLister(f.Informer().GetIndexer())
}
